-
  name: Docker Installation
  hosts: all

  tasks:
    - name: Update packages
      command:  sudo apt update
    - name: Install a few prerequisite packages which let apt use packages over HTTPS
      command: sudo apt install apt-transport-https ca-certificates curl software-properties-common
    - name: Add the GPG key for the official Docker repository to your system
      command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - name: Add the Docker repository to APT sources
      command: sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    - name: Make sure you are about to install from the Docker repo instead of the default Ubuntu repo
      command: apt-cache policy docker-ce
    - name: Install Docker 
      command: sudo apt install docker-ce
    - name: Check that it’s running
      command: sudo systemctl status docker
    - name: Add your username to the docker group
      command: sudo usermod -aG docker ${USER}

